app:
  debug: 'false'                # 调试模式
  tmp_dir: './data/tmp'         # 临时目录
  upload_dir: './data/upload'   # 存储拍摄/上传原始图片的目录
  feature_dir: './data/feature' # 初步加工原始图片、得到统一规格的图片存储目录
  feature_fmt: '.png'           # 特征图片格式


scheduler:                      # 定时任务
  work_time: 600                # 要求工作时长（分钟），默认为 8+2 小时（算上午休时间）
  checkin:                      # 上班卡
    begin_at: 9                 # 开始时间（小时）
    end_at: 11                  # 结束时间（小时）
    interval: 10                # 重试间隔（分钟）
  checkout:                     # 下班卡
    begin_at: 18                # 开始时间
    end_at: 23                  # 结束时间
    interval: 10                # 重试间隔（分钟）


database:
  dbtype: 'sqlite'
  dbpath: './data/db/ai-checkin.db'
  sqlpath: './data/script/ai-checkin-create.sql'


mediapipe:
  show_cv: 'true'               # 绘制画面的总开关（包括识别前的原画面，和识别后的关键坐标画面），关闭后相当于在后台运行，可以适当提高一些帧率
  match_min_sim: 0.75           # 匹配人脸的最小相似度


camera:                         # 摄像头
  index: 0                      # 设备索引号（默认 0）


adb:
  app: DingDing                         # 指定当前的 app 的签到步骤（adb 命令集）
  keep_live: 30                         # adb 连接保活时间（秒数）

DingDing:
  unlock_screen:                        # 解锁屏幕步骤
    - "input keyevent 224"              # 步骤 1: 唤醒屏幕
    - "wait 2"
    - "input swipe 300 1000 300 500"    # 步骤 2: 滑动屏幕，调出密码输入
    - "wait 2"
    - "input text <password>"           # 步骤 3: 输入锁屏密码
    - "wait 2"
    - "input keyevent 3"                # 步骤 4: 返回首页
    - "wait 2"
  open_app:                             # 打开用于签到的 APP 步骤
    - "input tap 411 1387"              # 步骤 1: 点击 APP 分组坐标
    - "wait 2"
    - "input tap 536 980"               # 步骤 2: 点击【钉钉】应用坐标
    - "wait 8"
  check_in:                             # 签到步骤
    - "input tap 537 2042"              # 步骤 1: 点击【工作台】按钮坐标
    - "wait 8"
    - "input tap 251 453"               # 步骤 2: 点击【全员】按钮坐标
    - "wait 8"
    - "input tap 248 1063"              # 步骤 3: 点击【考勤打卡】按钮坐标
    - "wait 8"
    - "input tap 540 1111"              # 步骤 4: 点击【上班/下班打卡】按钮坐标
    - "wait 8"
    - "input tap 982 164"               # 步骤 5: 点击【关闭】按钮坐标
    - "wait 5"
  lock_screen:                          # 锁屏
    - "input keyevent 223"

GT:
  unlock_screen:                        # 解锁屏幕步骤
    - "input keyevent 224"              # 步骤 1: 唤醒屏幕
    - "wait 2"
    - "input swipe 300 1000 300 500"    # 步骤 2: 滑动屏幕，调出密码输入
    - "wait 2"
    - "input text <password>"           # 步骤 3: 输入锁屏密码
    - "wait 2"
    - "input keyevent 3"                # 步骤 4: 返回首页
    - "wait 2"
  open_app:                             # 打开用于签到的 APP 步骤
    - "input tap 411 1387"              # 步骤 1: 点击 APP 分组坐标
    - "wait 2"
    - "input tap 800 706"               # 步骤 2: 点击【GT】应用坐标
    - "wait 2"
  check_in:                             # 签到步骤
    - "input tap 543 2051"              # 步骤 1: 点击【应用】按钮坐标
    - "wait 2"
    - "input tap 896 849"               # 步骤 2: 点击【去打卡】按钮坐标
    - "wait 10"
  lock_screen:                          # 锁屏
    - "input keyevent 223"
