app:
  debug: 'false'                # 调试模式
  tmp_dir: './data/tmp'         # 临时目录
  upload_dir: './data/upload'   # 存储拍摄/上传原始图片的目录
  feature_dir: './data/feature' # 初步加工原始图片、得到统一规格的图片存储目录
  feature_fmt: '.png'           # 特征图片格式

scheduler:                      # 定时任务
  work_time: 8                  # 工作时长
  on_work:                      # 上班卡
    begin_at: '09:00'           # 开始时间
    end_at: '11:00'             # 结束时间
    interval: 10                # 重试间隔（分钟）
  off_work:                     # 下班卡
    begin_at: '18:00'           # 开始时间
    end_at: '23:00'             # 结束时间
    interval: 10                # 重试间隔（分钟）

database:
  dbtype: 'sqlite'
  dbpath: './data/db/ai-checkin.db'
  sqlpath: './data/script/ai-checkin-create.sql'

mediapipe:                      # flase 时，结束监听后无法关闭后台进程
  show_cv: 'true'               # 绘制画面的总开关（包括识别前的原画面，和识别后的关键坐标画面），关闭后相当于在后台运行，可以适当提高一些帧率
  frequency: 2                  # 识别图像时的频率，每隔 N 帧识别一次（0 表示每帧都识别，值越大画面延迟越小，一般 2 为正常速率）
  resize_face:                  # 录入人脸时，框取人脸部分并调整保存的尺寸
    width: 512
    height: 512
  match_min_sim: 0.75           # 匹配人脸的最小相似度


video_capture_card:             # 视频采集卡
  index: 0                      # 设备索引号（默认 0）
  fourcc: 'MJPG'                # 输入格式（4个字符表示的视频编码格式）
  fps: 60                       # 输入帧速率
  frame:                        # 每帧的输入尺寸（即 AI 得到的屏幕尺寸，可执行 get_camera_size.py 脚本获得）
    width: 1366
    height: 768


adb:
  cmd_interval: 2                       # 命令执行间隔（秒）
  checkin: app1


app1:
  keep_live:                            # 保活命令
    - ""
  unlock_screen:                        # 解锁屏幕步骤
    - "input keyevent 224"              # 唤醒屏幕
    - "input swipe 300 1000 300 500"    # 滑动屏幕，调出密码输入
    - "input text <password>"           # 输入锁屏密码
    - "input keyevent 3"                # 返回首页
  open_app:                             # 打开用于签到的 APP
    - "input tap 411 1387"              # 步骤 1: 点击 APP 分组坐标
    - "input tap 800 706"               # 步骤 2: 点击目标 APP 坐标
  check_in:                             # 签到
    - "input tap 543 2051"              # 步骤 1: 点击 APP 内功能按钮坐标
    - "input tap 896 849"               # 步骤 2: 点击打卡按钮坐标
  lock_screen:                          # 锁屏
    - "input keyevent 223"              # 

app2:
  ......