app:
  debug: 'false'                # 调试模式
  annotated: 'false'            # 绘制标注
  image_format: '.png'          # 加工图片格式
  tmp_dir: './tmp'              # 存储拍摄/上传原始图片的临时目录
  mesh_dir: './face/01_mesh'            # 人脸网格后的图片存储目录
  detection_dir: './face/01_detection'  # 人脸检测后的图片存储目录
  alignment_dir: './face/02_alignment'  # 人脸对齐后的图片存储目录


scheduler:                      # 定时任务
  work_time: 540                # 要求工作时长（分钟），默认为 8+1.5 小时（算上午休时间）
  checkin:                      # 上班卡
    begin_at: 9                 # 开始时间（小时）
    end_at: 11                  # 结束时间（小时）
    interval: 5                 # 重试间隔（分钟）
  checkout:                     # 下班卡（注意：时间不能和上班卡有交集）
    begin_at: 18                # 开始时间
    end_at: 23                  # 结束时间
    interval: 5                 # 重试间隔（分钟）


database:
  dbtype: 'sqlite'
  dbpath: './data/db/ai-checkin.db'
  sqlpath: './data/script/ai-checkin-create.sql'
  check_same_thread: False
  

mediapipe:
  show_image: 'false'             # CV 绘制图像画面的总开关
  show_video: 'false'             # CV 绘制视频画面的总开关
  match_min_sim: 0.70             # 匹配人脸的最小相似度
  standard_dir: './data/standard' # 已生成的标准脸尺寸目录
  standard_face: '512x512'        # 当前选择的标准脸尺寸


dlib:
  model_dir: './data/model'       # dlib 模型目录（主要用于计算人脸特征）
  model:
    detection: 'shape_predictor_68_face_landmarks.dat'    # 人脸检测模型
    feature: 'dlib_face_recognition_resnet_model_v1.dat'  # 人脸特征提取模型


camera:           # 摄像头
  index: 0        # 设备索引号（默认 0）
  fourcc: 'MJPG'  # 输入格式（4个字符表示的视频编码格式）
  fps: 60         # 输入帧速率
  frame:          # 每帧的输入尺寸（即 AI 得到的屏幕尺寸，可执行 get_camera_size.py 脚本获得）
    width: 1280
    height: 960


adb:
  app: DingDing                         # 指定当前的 app 的签到步骤（adb 命令集）
  keep_live: 30                         # adb 连接保活时间（秒数）

DingDing:
  unlock_screen:                        # 解锁屏幕步骤
    - "input keyevent 224"              # 步骤 1: 唤醒屏幕
    - "wait 2"
    - "input swipe 300 1000 300 500"    # 步骤 2: 滑动屏幕，调出密码输入
    - "wait 2"
    - "input text <password>"           # 步骤 3: 输入锁屏密码
    - "wait 2"
    - "input keyevent 3"                # 步骤 4: 返回首页
    - "wait 2"
  open_app:                             # 打开用于签到的 APP 步骤
    - "input tap 411 1387"              # 步骤 1: 点击 APP 分组坐标
    - "wait 2"
    - "input tap 536 980"               # 步骤 2: 点击【钉钉】应用坐标
    - "wait 7"
  check_in:                             # 签到步骤
    - "input tap 537 2042"              # 步骤 1: 点击【工作台】按钮坐标
    - "wait 3"
    - "input tap 251 453"               # 步骤 2: 点击【全员】按钮坐标
    - "wait 3"
    - "input tap 248 1063"              # 步骤 3: 点击【考勤打卡】按钮坐标
    - "wait 7"
    - "input tap 540 1111"              # 步骤 4: 点击【上班/下班打卡】按钮坐标
    - "wait 8"
    - "input tap 982 164"               # 步骤 5: 点击【关闭】按钮坐标
    - "wait 5"
  lock_screen:                          # 锁屏
    - "input keyevent 223"

GT:
  unlock_screen:                        # 解锁屏幕步骤
    - "input keyevent 224"              # 步骤 1: 唤醒屏幕
    - "wait 2"
    - "input swipe 300 1000 300 500"    # 步骤 2: 滑动屏幕，调出密码输入
    - "wait 2"
    - "input text <password>"           # 步骤 3: 输入锁屏密码
    - "wait 2"
    - "input keyevent 3"                # 步骤 4: 返回首页
    - "wait 2"
  open_app:                             # 打开用于签到的 APP 步骤
    - "input tap 411 1387"              # 步骤 1: 点击 APP 分组坐标
    - "wait 3"
    - "input tap 800 706"               # 步骤 2: 点击【GT】应用坐标
    - "wait 7"
  check_in:                             # 签到步骤
    - "input tap 543 2051"              # 步骤 1: 点击【应用】按钮坐标
    - "wait 3"
    - "input tap 896 849"               # 步骤 2: 点击【去打卡】按钮坐标（第一次可能会触发 GPS 检查，多点一次）
    - "wait 5"
    - "input tap 896 849"               # 步骤 2: 点击【去打卡】按钮坐标
    - "wait 5"
  lock_screen:                          # 锁屏
    - "input keyevent 223"
